SNS_TOPIC_ARN = "arn:aws:sns:ap-south-1:247564879499:Pragaty.fifo"

# POST QUEUE
POST_OP_QUEUE = "https://sqs.ap-south-1.amazonaws.com/247564879499/PostOpQueue.fifo"

# EVENTS
POST_CREATE = "POST_CREATE"
POST_LIKE = "POST_LIKE"
POST_COMMENT = "POST_COMMENT"
FOLLOW_USER = "FOLLOW_USER"


# QUEUE SETTINGS
MAX_NUMBER = 100
WAIT_TIME = 30
VISIBILITY_TIMEOUT = 60
