branch-defaults:
  staging:
    environment: null
global:
  application_name: pragaty-backend
  branch: null
  default_ec2_keyname: administrator-key-pair
  default_platform: Docker running on 64bit Amazon Linux
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
