version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build-pragaty-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Building Docker Image
          command: |
            docker build -t udayshankarsingh/koala-backend:$CIRCLE_BUILD_NUM .
      - run:
          name: Pushing image to dockerhub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker push udayshankarsingh/koala-backend:$CIRCLE_BUILD_NUM
  eb-demo:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - eb/setup
      - run:
          command: |
            eb status
          name: You may now use the EB CLI within this job
      - run:
          name: Deploying docker image
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            sed -i'' -e "s;%BUILD_NUM%;$CIRCLE_BUILD_NUM;g" Dockerrun.aws.json
            eb use $CIRCLE_BRANCH
            eb deploy -l $CIRCLE_BUILD_NUM
#  eb/deploy:
#    docker:
#      - image: 'udayshankarsingh/koala-backend:born'
#        auth:
#          username: $DOCKERHUB_USERNAME
#          password: $DOCKERHUB_PASSWORD
#    steps:
#      - checkout
#      - run:
#          name: Printing some basic env variables to validate their pick-ups
#          command: |
#            echo $AWS_DEFAULT_REGION
#            echo $CIRCLE_BRANCH
#      - run:
#          name: Deploying docker image
#          command: |
#            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
#            sed -i'' -e "s;%BUILD_NUM%;$CIRCLE_BUILD_NUM;g" Dockerrun.aws.json
#            eb use $CIRCLE_BRANCH
#            eb deploy -l $CIRCLE_BUILD_NUM
workflows:
  version: 2
  elastic-beanstalk-workflow:
    jobs:
      - build-pragaty-docker:
          filters:
            branches:
              only: staging
      - eb-demo:
          requires:
            - build-pragaty-docker
#      - eb/deploy:
#          context: aws-creds
#          environment-name: $CIRCLE_BRANCH
#          filters:
#            branches:
#              only:
#                - staging
#          label: version-<<pipeline.number>>
#          requires:
#            - build-pragaty-docker

