version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Building Docker Image
          command: |
            docker build -t udayshankarsingh/koala-backend:pragaty-<<pipeline.number>> .
      - run:
          name: Pushing image to dockerhub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker push udayshankarsingh/koala-backend:pragaty-<<pipeline.number>>
  eb-deploy:
    machine: true
    steps:
      - eb/setup
      - run:
          command: |
            eb use $CIRCLE_BRANCH
            eb status
          name: You may now use the EB CLI within this job
      - run:
          name: Deploying docker image
          command: |
            echo "This is pipeline ID - "<<pipeline.number>>
            sed -i'' -e "s;%BUILD_NUM%;<<pipeline.number>>;g" Dockerrun.aws.json
            eb deploy -l pragaty-<<pipeline.number>>
workflows:
  version: 2
  elastic-beanstalk-workflow:
    jobs:
      - build-docker:
          filters:
            branches:
              only:
              - master
              - staging
      - hold:
          type: approval
          requires:
            - build-docker
      - eb-deploy:
          requires:
            - hold