version: 2.1 # circle ci version
jobs:
  Build-Pragaty-Docker:
    machine: true
    steps:
      - run:
          name: Build Docker Image
          command: |
            echo 'Building docker image'
            docker build -t udayshankarsingh/koala-backend:born .
            docker login --username udayshankarsingh --password koala1docker
            docker push udayshankarsingh/koala-backend:born