version: 2.1
jobs:
  build-pragaty-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Building Docker Image
          command: |
            docker build -t udayshankarsingh/koala-backend:born .
      - run:
          name: Pushing image to dockerhub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker push udayshankarsingh/koala-backend:$CIRCLE_BUILD_NUM
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - run:
          name: Printing some basic env variables to validate their pick-ups
          command: |
            echo $AWS_DEFAULT_REGION
            echo pragaty-$CIRCLE_BRANCH
      - run:
          name: Deploying docker image
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            sed -i'' -e "s;%BUILD_NUM%;$CIRCLE_BUILD_NUM;g" Dockerrun.aws.json
            eb use pragaty-$CIRCLE_BRANCH
            eb deploy -l $CIRCLE_BUILD_NUM
workflows:
  version: 2
  elastic-beanstalk-workflow:
    jobs:
#      - build-pragaty-docker:
#          filters:
#            branches:
#              only: staging
      - deploy:
          context: aws-creds
          filters:
            branches:
              only:
                - staging
#          requires:
#            - build-pragaty-docker

