version: 2.1 # circle ci version
Build-Pragaty-Docker:
  steps:
    - run:
        name: Build Docker Image
        command: |
          echo 'Building docker image'
          docker build -t udayshankarsingh/koala-backend:born .
          docker login --username udayshankarsingh --password koala1docker
          docker push udayshankarsingh/koala-backend:born
workflows:
  build-deploy:
    jobs:
      - build_development_branch:
          filters:
            branches:
              only: development
      - Build-Pragaty-Docker
