version: 2.1 # circle ci version
jobs:
  build-pragaty-docker:
    machine: true
    steps:
      - run:
          name: Build Docker Image
          command: |
            echo 'Building docker image'
            docker build -t udayshankarsingh/koala-backend:born .
            docker login --username udayshankarsingh --password koala1docker
            docker push udayshankarsingh/koala-backend:born
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-pragaty-docker:
          filters:
            branches:
              only: development
