version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build-pragaty-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Building Docker Image
          command: |
            docker build -t udayshankarsingh/koala-backend:born .
      - run:
          name: Pushing image to dockerhub
          command: |
            docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD
            docker push udayshankarsingh/koala-backend:born
  eb/deploy:
    docker:
      - image: 'udayshankarsingh/koala-backend:born'
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: "echo environment variables from aws-creds context"
          command: |
            echo $AWS_DEFAULT_REGION
            echo pragaty-$CIRCLE_BRANCH
      - run:
          name: Deploying docker image
          command: |
            eb deploy pragaty-$CIRCLE_BRANCH
            eb status
workflows:
  version: 2
  elastic-beanstalk-workflow:
    jobs:
      - build-pragaty-docker:
          filters:
            branches:
              only: staging
      - eb/deploy:
          context: aws-creds
          environment-name: pragaty-$CIRCLE_BRANCH
          filters:
            branches:
              only:
                - staging
          label: version-$CIRCLE_BUILD_NUM
          requires:
            - build-pragaty-docker

