SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 1440

# API CONSTANTS
REQUEST_SKIP_DEFAULT = 0
REQUEST_PAGE_NUMBER = 1
REQUEST_LIMIT = 25

# COLLECTION SUBSET LIMIT
EMBEDDED_COLLECTION_LIMIT = 10


# APP CONSTANTS
ALL = "all"
BOOKMARKED = "bookmarked"
SHORTLISTED = "shortlisted"
REJECTED = "rejected"
ALL_JOBS = "all_jobs"
APPLIED_JOBS = "applied_jobs"
SAVED_JOBS = "saved_jobs"
FRESHERS_JOBS = "freshers_jobs"
FILTERED_JOBS = "filtered_jobs"

GOLD = "gold"
NORMAL = "normal"

# S3 Constants
S3_IMAGE_BUCKET_PROFILE = "koala-profile-images"
S3_IMAGE_BUCKET_POSTS = "koala-posts-images"
S3_IMAGE_BUCKET_COMPANY_BANNER = "koala-company-banners"
