DB_NAME = "koala-backend"
USERS = "users"
GIG_TYPE = "gig-types"
OP_CITIES = "op-cities"
OP_AREAS = "op-areas"
COMPANIES = "companies"
JOBS = "jobs"
SEQUENCE = "sequence"

# JOB MASTER
BENEFITS = "benefits"
DOCUMENTS = "documents"
HIRING_TYPES = "hiring_types"
JOB_TYPES = "job_types"
LANGUAGES = "languages"
QUALIFICATIONS = "qualifications"
SKILLS = "skills"
